In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../python/data/lfb_jan2013-mar2016 original.csv',sep=",")
data

c:\Users\Thang\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2723: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


IncidentNumber DateOfCall TimeOfCall    IncidentGroup  \
0                  1131     1.I.13    0:02:06      False Alarm   
1                  4131     1.I.13    0:02:09      False Alarm   
2                  5131     1.I.13    0:02:54      False Alarm   
3                  2131     1.I.13    0:03:02             Fire   
4                  3131     1.I.13    0:03:03      False Alarm   
5                  6131     1.I.13    0:05:16             Fire   
6                  7131     1.I.13    0:05:24      False Alarm   
7                 10131     1.I.13    0:08:18      False Alarm   
8                 13131     1.I.13    0:12:16             Fire   
9                 15131     1.I.13    0:16:39      False Alarm   
10                17131     1.I.13    0:18:59             Fire   
11                19131     1.I.13    0:19:34      False Alarm   
12                22131     1.I.13    0:22:26  Special Service   
13                24131     1.I.13    0:25:55  Special Service   
14                25131     1.I.13    0:26:33  Special Service   
15                27131     1.I.13    0:38:07      False Alarm   
16                31131     1.I.13    0:50:18             Fire   
17                32131     1.I.13    0:57:09      False Alarm   
18                33131     1.I.13    0:59:05             Fire   
19                34131     1.I.13    0:59:13      False Alarm   
20                43131     1.I.13    1:01:19      False Alarm   
21                44131     1.I.13    1:01:56  Special Service   
22                46131     1.I.13    1:03:17             Fire   
23                47131     1.I.13    1:04:46  Special Service   
24                50131     1.I.13    1:06:36  Special Service   
25                51131     1.I.13    1:06:56  Special Service   
26                53131     1.I.13    1:08:08  Special Service   
27                54131     1.I.13    1:14:17             Fire   
28                57131     1.I.13    1:17:25      False Alarm   
29                60131     1.I.13    1:23:57  Special Service   
...                 ...        ...        ...              ...   
322113  038276-31032016  31.III.16   21:42:46             Fire   
322114  038277-31032016  31.III.16   21:47:06             Fire   
322115  038278-31032016  31.III.16   21:52:55      False Alarm   
322116  038279-31032016  31.III.16   21:54:10      False Alarm   
322117  038281-31032016  31.III.16   22:02:46      False Alarm   
322118  038282-31032016  31.III.16   22:06:09             Fire   
322119  038283-31032016  31.III.16   22:07:13  Special Service   
322120  038284-31032016  31.III.16   22:08:36  Special Service   
322121  038286-31032016  31.III.16   22:14:51      False Alarm   
322122  038287-31032016  31.III.16   22:15:50      False Alarm   
322123  038288-31032016  31.III.16   22:17:35      False Alarm   
322124  038289-31032016  31.III.16   22:24:04             Fire   
322125  038290-31032016  31.III.16   22:26:11             Fire   
322126  038291-31032016  31.III.16   22:26:54             Fire   
322127  038292-31032016  31.III.16   22:27:32             Fire   
322128  038295-31032016  31.III.16   22:29:55             Fire   
322129  038298-31032016  31.III.16   22:32:27      False Alarm   
322130  038300-31032016  31.III.16   22:33:06             Fire   
322131  038305-31032016  31.III.16   22:35:05  Special Service   
322132  038306-31032016  31.III.16   22:49:11      False Alarm   
322133  038308-31032016  31.III.16   22:57:33             Fire   
322134  038309-31032016  31.III.16   23:00:04  Special Service   
322135  038310-31032016  31.III.16   23:04:51  Special Service   
322136  038311-31032016  31.III.16   23:05:26  Special Service   
322137  038315-31032016  31.III.16   23:16:12             Fire   
322138  038317-31032016  31.III.16   23:33:19      False Alarm   
322139  038318-31032016  31.III.16   23:37:45  Special Service   
322140  038319-31032016  31.III.16   23:46:41             Fire   
322141  038320-31032016  31.III.16   23:47:28    

In [143]:
#no null values in easting and northing
cleanedData = data[data["Easting_m"].notnull()][["Easting_m","Northing_m","IncidentGroup","TimeOfCall"]]

#convert easting northing to lat/lon
#might need to install BNG, -> pip install utm
import pyproj

bng = pyproj.Proj(init='epsg:27700')
wgs84 = pyproj.Proj(init='epsg:4326')

# AL1 1AB - pyproj.transform(from,to,easting,northing)
lon,lat = pyproj.transform(bng,wgs84, cleanedData["Easting_m"].values, cleanedData["Northing_m"].values)
cleanedData["lat"] = lat;
cleanedData["lon"] = lon;
#cleanedData

#adding hours of call to cleandedData
lst = cleanedData["TimeOfCall"].str.split(':').tolist()
timeCall = [np.int_(item[0]) for item in lst]
cleanedData["HourOfCall"] = timeCall

In [47]:
import json
import numpy as np

from sklearn.cluster import MiniBatchKMeans

#create new dataframe for output dataset
df = pd.DataFrame(data = cleanedData, columns=["lat","lon"])

input = df.values.tolist()
output = input

for i in range(2,7):
    print "k-" + str(i)
    mbk = MiniBatchKMeans(init='k-means++', n_clusters=i, batch_size=45,
                          n_init=10, max_no_improvement=10, verbose=0)
    mbk.fit(input)
    mbk_means_labels = mbk.labels_
    mbk_means_cluster_centers = mbk.cluster_centers_
    mbk_means_labels_unique = np.unique(mbk_means_labels)

    
    print mbk_means_cluster_centers

    cleanedData["kmeans"+str(i)] = mbk_means_labels
    

#for every k-# of a point there is a label(code) which indicates the cluster the point is in
#the code is used for visualization in D3 
df = pd.DataFrame(data = cleanedData, columns=["lat","lon","kmeans2","kmeans3","kmeans4","kmeans5","kmeans6"])

#export to json
df[::3].reset_index().to_json("cluster.json",orient='records')

k-2
[[  5.14988119e+01  -2.79139605e-01]
 [  5.15094002e+01  -4.02149503e-02]]
k-3
[[ 51.50551864  -0.11829686]
 [ 51.51118076  -0.35562883]
 [ 51.51517723   0.08816218]]
k-4
[[ 51.49594442  -0.17385745]
 [ 51.5086977    0.11172957]
 [ 51.51517077  -0.06225949]
 [ 51.50635049  -0.36965009]]
k-5
[[  5.15404821e+01   1.15502169e-01]
 [  5.14336954e+01  -1.73381276e-01]
 [  5.15426238e+01  -1.10882926e-01]
 [  5.14482143e+01   2.32863037e-03]
 [  5.15172934e+01  -3.53647672e-01]]
k-6
[[ 51.54381876  -0.08661409]
 [ 51.50029165  -0.20021947]
 [ 51.51459436  -0.38743269]
 [ 51.55816229   0.19001293]
 [ 51.3955831   -0.12177639]
 [ 51.48589303   0.05500602]]


[11 11]


In [144]:
#Training vars
dataSize = len(cleanedData)
learnSizeKoef = np.int_(0.8 * dataSize)

#splitting data into learning and testing sets
knnLearnData = cleanedData[["lat","lon","HourOfCall"]][:learnSizeKoef].values.tolist()
knnLearnLabels = cleanedData["IncidentGroup"][:learnSizeKoef].values.tolist()

knnTestData = cleanedData[["lat","lon","HourOfCall"]][learnSizeKoef:dataSize].values.tolist()
knnTestLabels = cleanedData["IncidentGroup"][learnSizeKoef:dataSize].values.tolist()

#clean double brackets
knnLearnLabels = np.ravel(knnLearnLabels)
knnTestLabels = np.ravel(knnTestLabels)

In [148]:
#KNN machine learning part

#Training parameters
X = knnLearnData
#labels
y = knnLearnLabels
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=10,weights = 'distance')
neigh.fit(X, y) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='distance')

In [149]:
#KNN test predictions
#print neigh.predict([[51.54381876 , -0.08661409],[51.49594442,  -0.17385745]])
#Mean accuracy (prumerna presnost)
neigh.score(knnTestData,knnTestLabels)


0.53483021725202395