In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../python/data/lfb_jan2013-mar2016 original.csv',sep=",")

c:\Users\Thang\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2723: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [53]:
oj = data[:5][["Easting_m","Northing_m"]]
oj["lat"] = 9
#print oj
eas = oj.get("Easting_m")
nor = oj.get("Northing_m")

#no null values in easting and northing
cleanedData = data[data["Easting_m"].notnull()][["Easting_m","Northing_m"]]


In [62]:
#convert easting northing to lat/lon
#might need to install BNG, -> pip install utm
import pyproj

bng = pyproj.Proj(init='epsg:27700')
wgs84 = pyproj.Proj(init='epsg:4326')

# AL1 1AB - pyproj.transform(from,to,easting,northing)
lon,lat = pyproj.transform(bng,wgs84, cleanedData["Easting_m"].values, cleanedData["Northing_m"].values)
cleanedData["lat"] = lat;
cleanedData["lon"] = lon;
#cleanedData

In [61]:
import json
import numpy as np

from sklearn.cluster import MiniBatchKMeans

#create new dataframe for output dataset
df = pd.DataFrame(data = cleanedData, columns=["lat","lon"])

input = df.values.tolist()
output = input

for i in range(2,7):
    print "k-" + str(i)
    mbk = MiniBatchKMeans(init='k-means++', n_clusters=i, batch_size=45,
                          n_init=10, max_no_improvement=10, verbose=0)
    mbk.fit(input)
    mbk_means_labels = mbk.labels_
    mbk_means_cluster_centers = mbk.cluster_centers_
    mbk_means_labels_unique = np.unique(mbk_means_labels)

    
    print mbk_means_cluster_centers

    cleanedData["kmeans"+str(i)] = mbk_means_labels
    

#for every k-# of a point there is a label(code) which indicates the cluster the point is in
#the code is used for visualization in D3 
df = pd.DataFrame(data = cleanedData, columns=["lat","lon","kmeans2","kmeans3","kmeans4","kmeans5","kmeans6"])

#export to json
df[::3].reset_index().to_json("cluster.json",orient='records')


k-2
[[  5.15045833e+01   4.71093733e-03]
 [  5.14975219e+01  -2.14137227e-01]]
k-3
[[ 51.5053299   -0.12299298]
 [ 51.5058915   -0.34336555]
 [ 51.52377608   0.06725369]]
k-4
[[ 51.5116293    0.08708305]
 [ 51.50733119  -0.34258377]
 [ 51.53935083  -0.114302  ]
 [ 51.41871873  -0.12112792]]
k-5
[[ 51.49335058  -0.22922312]
 [ 51.54124358  -0.09639724]
 [ 51.51699208   0.10596292]
 [ 51.4160444   -0.07506114]
 [ 51.51364582  -0.39459561]]
k-6
[[  5.13907953e+01  -1.12877981e-01]
 [  5.15186291e+01  -1.08035764e-01]
 [  5.15026271e+01   8.41976582e-02]
 [  5.15018373e+01  -3.73294554e-01]
 [  5.15183389e+01  -2.22719607e-01]
 [  5.15981924e+01  -4.35403401e-02]]


lat       lon  kmeans2  kmeans3  kmeans4  kmeans5  kmeans6
0       51.549006 -0.192508        1        0        2        0        4
1       51.556094 -0.336755        1        1        1        4        3
2       51.493515 -0.237460        1        1        1        0        4
3       51.513620 -0.159464        1        0        2        1        1
4       51.509828 -0.080011        0        0        2        1        1
5       51.565753 -0.258720        1        1        1        0        4
6       51.541334 -0.198278        1        0        2        0        4
9       51.481386 -0.436728        1        1        1        4        3
15      51.513567 -0.087579        0        0        2        1        1
16      51.376437 -0.072162        0        0        3        3        0
19      51.549523 -0.309836        1        1        1        4        3
20      51.511961 -0.101640        0        0        2        1        1
21      51.494019 -0.367394        1        1        1        4        3
22      51.560134  0.063464        0        2        0        2        2
26      51.501698 -0.123275        1        0        2        1        1
27      51.596615  0.173193        0        2        0        2        2
30      51.590727 -0.103353        0        0        2        1        5
36      51.517124 -0.205748        1        0        2        0        4
40      51.491356 -0.194314        1        0        2        0        4
41      51.547680 -0.344561        1        1        1        4        3
43      51.568217  0.011234        0        2        0        2        5
45      51.561304  0.080715        0        2        0        2        2
50      51.492345 -0.136783        1        0        2        1        1
57      51.479118 -0.123353        1        0        3        1        1
58      51.480304 -0.056480        0        0        2        3        1
60      51.533908  0.058010        0        2        0        2        2
61      51.507718  0.040704        0        2        0        2        2
67      51.484210  0.073516        0        2        0        2        2
68      51.483199  0.073758        0        2        0        2        2
69      51.463780 -0.083499        0        0        3        3        1
...           ...       ...      ...      ...      ...      ...      ...
322092  51.520074 -0.134296        1        0        2        1        1
322095  51.530598 -0.033707        0        0        2        1        5
322096  51.497591 -0.392925        1        1        1        4        3
322097  51.404868 -0.281157        1        1        1        0        4
322098  51.438197  0.005632        0        2        0        3        2
322099  51.509200  0.017914        0        2        0        2        2
322102  51.649231 -0.086182        0        0        2        1        5
322103  51.573646 -0.070049        0        0        2        1        5
322104  51.509218  0.017915        0        2        0        2        2
322108  51.461231 -0.013066        0        2        0        3        2
322110  51.506064 -0.136540        1        0        2        1        1
322111  51.494783 -0.160771        1        0        2        0        1
322112  51.385250  0.137710        0        2        0        2        2
322113  51.497641 -0.397879        1        1        1        4        3
322114  51.548986 -0.002206        0        2        0        1        5
322115  51.426718 -0.175746        1        0        3        0        0
322116  51.499822 -0.162153        1        0        2        0        1
322118  51.515970 -0.049485        0        0        2        1        1
322121  51.499822 -0.162153        1        0        2        0        1
322123  51.402539 -0.105024        1        0        3        3        0
322124  51.547706 -0.368863        1        1        1        4        3
322125  51.514241 -0.149783        1        0        2        1        1
322126  51.552817  0.191718        0        2        0        2        2